// Real pointer/keyboard and audio-context checks. Progress visuals use explicit API fixtures.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),fs=require('fs'),path=require('path'),assert=require('assert');
const url=process.env.DEMO_URL||'http://127.0.0.1:8877',out=process.env.BROWSER_OUTPUT||'data/web-preview-evidence';fs.mkdirSync(out,{recursive:true});
const pause=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),c=await b.newContext({viewport:{width:1440,height:1000}}),p=await c.newPage(),errors=[];
 p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{window.__audio=[];const Native=window.AudioContext;window.AudioContext=class extends Native{constructor(...args){super(...args);this.played=[];window.__audio.push(this)}createOscillator(){const o=super.createOscillator(),start=o.start.bind(o);o.start=(t)=>{this.played.push(o.frequency.value);return start(t)};return o}}});
 await p.goto(url);await p.getByRole('heading',{name:'情绪搭建画板'}).waitFor();const state=()=>p.evaluate(()=>fetch('/api/project').then(r=>r.json()));const initial=await state();assert.equal(initial.grid_count,8);assert.equal(initial.total_ticks,15360);
 await p.getByRole('button',{name:'选择 A1',exact:true}).click();assert.equal(await p.evaluate(()=>window.__audio.length),0);
 await p.getByRole('button',{name:'播放 A1',exact:true}).click();await p.waitForFunction(()=>window.__audio.at(-1)?.state==='running'&&window.__audio.at(-1).played.length>0);assert((await p.locator('.player-title strong').innerText()).startsWith('A1'));
 await p.getByRole('button',{name:'播放 A2',exact:true}).click();await p.waitForFunction(()=>window.__audio.length===2&&window.__audio[0].state==='closed'&&window.__audio[1].state==='running');const freq=await p.evaluate(()=>window.__audio.at(-1).played[0]);const a2=initial.materials.find(m=>m.display_name==='A2'&&m.library_visible);assert(Math.abs(freq-440*2**((a2.notes[0].pitch-69)/12))<.1);
 await p.getByLabel('停止',{exact:true}).click();await p.waitForFunction(()=>window.__audio.every(c=>c.state==='closed'));await p.getByLabel('播放',{exact:true}).click();await p.waitForFunction(()=>window.__audio.at(-1).state==='running');await p.getByLabel('停止',{exact:true}).click();
 await p.getByRole('button',{name:'播放 A1',exact:true}).focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>window.__audio.at(-1).state==='running');await p.getByLabel('停止',{exact:true}).click();
 await p.getByRole('button',{name:'手绘强度',exact:true}).click();await pause(350);const r=await p.locator('svg.canvas').boundingBox(),W=850,H=340,total=15360;const X=t=>r.x+34+t/total*(W-50),Y=v=>r.y+H-45-v*(H-90);
 await p.mouse.move(X(0)+2,Y(.2));await p.mouse.down();for(let i=0;i<=32;i++){const t=i*480,v=t<=14400?.2+.7*t/14400:.9-.65*(t-14400)/960;await p.mouse.move(X(t),Y(v),{steps:2})}await Promise.all([p.waitForResponse(v=>v.url().endsWith('/api/edit')&&v.request().method()==='POST'),p.mouse.up()]);await p.getByRole('button',{name:'选择 / 调整',exact:true}).click();let drawn=await state();assert(drawn.intensity_points.some(v=>v.tick>13440&&v.tick<15360));
 await Promise.all([p.waitForResponse(v=>v.url().endsWith('/api/edit')),p.getByLabel('减少四拍').click()]);assert.equal((await state()).grid_count,7);assert.equal(await p.locator('.error').count(),0);
 await Promise.all([p.waitForResponse(v=>v.url().endsWith('/api/edit')),p.getByTitle('撤销',{exact:true}).click()]);assert.equal((await state()).fingerprint,drawn.fingerprint);
 await Promise.all([p.waitForResponse(v=>v.url().endsWith('/api/edit')),p.getByTitle('重做',{exact:true}).click()]);
 await p.getByRole('button',{name:'选择 A1',exact:true}).click();await p.getByLabel('放置格').fill('7');await Promise.all([p.waitForResponse(v=>v.url().endsWith('/api/edit')),p.getByRole('button',{name:'放入所选积木',exact:true}).click()]);const beforeClear=await state();
 const response=await Promise.all([p.waitForResponse(v=>v.url().endsWith('/api/edit')),p.getByLabel('减少四拍').click()]);assert.equal(response[0].status(),422);assert((await p.locator('.error').innerText()).includes('清空画板'));
 await Promise.all([p.waitForResponse(v=>v.url().endsWith('/api/edit')),p.getByRole('button',{name:'清空画板',exact:true}).click()]);let cleared=await state();assert.equal(cleared.grid_count,7);assert.equal(cleared.placements.length,0);assert.equal(cleared.intensity_points.length,2);assert.deepEqual(cleared.materials,beforeClear.materials);assert.equal(await p.locator('.error').count(),0);
 await Promise.all([p.waitForResponse(v=>v.url().endsWith('/api/edit')),p.getByTitle('撤销',{exact:true}).click()]);assert.equal((await state()).fingerprint,beforeClear.fingerprint);await Promise.all([p.waitForResponse(v=>v.url().endsWith('/api/edit')),p.getByTitle('重做',{exact:true}).click()]);await Promise.all([p.waitForResponse(v=>v.url().endsWith('/api/edit')),p.getByLabel('减少四拍').click()]);assert.equal((await state()).grid_count,6);
 await Promise.all([p.waitForResponse(v=>v.url().endsWith('/api/session')),p.getByRole('button',{name:'载入旋律 · 新体验',exact:true}).click()]);assert.equal((await state()).grid_count,8);await p.getByRole('button',{name:'选择 A1',exact:true}).click();await p.getByRole('button',{name:'放入所选积木',exact:true}).click();await p.locator('svg.canvas .block').waitFor();await p.screenshot({path:path.join(out,'light.png'),fullPage:true});
 // The following controlled states validate frontend feedback, not actual music generation.
 let phase='BASE_COMPLETION',status='RUNNING',fixture=await state();const progression=[];
 await p.route('**/api/generate',route=>route.fulfill({json:{id:'preview-progress-fixture',status:'QUEUED'}}));await p.route('**/api/jobs/preview-progress-fixture',route=>route.fulfill({json:{status,error:status==='FAILED'?'测试错误':null,progress:{phase,message:'BACKEND DETAIL MUST NOT BE SHOWN'}}}));await p.route('**/api/jobs/preview-progress-fixture/cancel',route=>{status='CANCELLED';return route.fulfill({json:{status}})});
 await p.getByRole('button',{name:'生成方案',exact:true}).click();await p.getByRole('progressbar').waitFor();for(const next of ['BASE_COMPLETION','BRIDGE_DECISION','CONNECTIONS','BOUNDARIES','VALIDATION','ARRANGEMENT','RENDERING']){phase=next;await pause(2100);const value=+(await p.getByRole('progressbar').getAttribute('aria-valuenow'));progression.push(value);assert.equal((await p.locator('.progress-node').count()),8);assert(!(await p.locator('.generation-progress').innerText()).includes('BACKEND DETAIL'));}
 assert.deepEqual(progression,[1,2,3,4,5,6,7]);phase='BRIDGE_DECISION';await pause(2100);assert.equal(+(await p.getByRole('progressbar').getAttribute('aria-valuenow')),7);
 await p.screenshot({path:path.join(out,'progress-light.png'),fullPage:true});await p.getByLabel('切换明暗主题').click();await pause(300);await p.screenshot({path:path.join(out,'progress-dark.png'),fullPage:true});
 const overflow=[];for(const width of [1020,1440,390]){await p.setViewportSize({width,height:width===390?844:1000});await pause(200);overflow.push({width,overflow:await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)});assert.equal(overflow.at(-1).overflow,false);await p.screenshot({path:path.join(out,'progress-'+width+'.png'),fullPage:true})}
 await p.setViewportSize({width:1440,height:1000});await p.getByRole('button',{name:'取消生成',exact:true}).click();await p.getByText('已取消生成',{exact:true}).waitFor();assert.equal(+(await p.getByRole('progressbar').getAttribute('aria-valuenow')),0);
 status='SUCCEEDED';fixture={...fixture,candidates:[{id:'preview-candidate-fixture',ready:true,applied:false,changed:true}]};await p.route('**/api/project',route=>route.fulfill({json:fixture}));await p.getByRole('button',{name:'生成方案',exact:true}).click();await p.getByText('方案已生成',{exact:true}).waitFor();assert.equal(+(await p.getByRole('progressbar').getAttribute('aria-valuenow')),8);await p.screenshot({path:path.join(out,'complete-dark.png'),fullPage:true});
 status='FAILED';fixture={...fixture,candidates:[]};await p.getByRole('button',{name:'生成方案',exact:true}).click();await p.getByText('生成未完成',{exact:true}).waitFor();assert((await p.locator('.error').innerText()).includes('测试错误'));
 assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync(path.join(out,'browser-preview.json'),JSON.stringify({real_source_one_click_play:true,selection_silent:true,rapid_source_switch:true,player_replay:true,keyboard_audition:true,default_beats:32,real_pointer_trace_shrink:true,tail_music_not_truncated:true,clear_single_undo:true,materials_preserved:true,progress_states_fixture:true,progression,progress_monotonic_across_second_candidate:true,details_hidden:true,overflow,errors},null,2));await b.close();console.log('BROWSER_PREVIEW_PASS')})().catch(e=>{console.error(e);process.exit(1)});
