import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import brandIcon from './assets/emoblocks-icon.png';
import {GenerationProgress,progressStep,type ProgressState} from './GenerationProgress';
import {ResultBlocks,type ResultSegment} from './ResultBlocks';
type Note={pitch:number;start_tick:number;duration_tick:number;velocity:number};
type Material={id:string;label:string;display_name:string;library_visible:boolean;length_ticks:number;notes:Note[];kind:string};
type Point={tick:number;level:number};
type Block={id:string;material_id:string;base_snapshot:Material;start_tick:number;length_ticks:number;emotion:string};
type Candidate={id:string;ready:boolean;applied:boolean;changed:boolean;mode?:string;result?:{segments:ResultSegment[]}};
type Sample={id:string;label:string;composer:string;source:string;credit:string;license:string;license_url:string;adaptation:string};
type Project={fingerprint:string;bpm:number;grid_count:number;total_ticks:number;materials:Material[];placements:Block[];intensity_points:Point[];protections:{kind:string;start_tick:number;end_tick:number}[];blanks:{id:string;start_tick:number;end_tick:number}[];memory:{state:string;placement_id:string|null};candidates:Candidate[];can_undo:boolean;can_redo:boolean};
const emotions:Record<string,[string,string]>={calm:['平静／安定','#c9ded8'],hope:['温暖／希望','#e9ddba'],sad:['悲伤／失落','#ccd6e9'],suspense:['悬疑／不安','#dccfe4'],crisis:['紧张／危机','#e9cbd0'],resolve:['振奋／坚定','#d4e2c9']};
const methods:Record<string,string>={variant:'局部变化',answer:'动机回答',counter:'副旋律',rhythm:'节奏变化',develop:'乐句发展',density:'疏密变化'};
async function api(path:string,body?:unknown){const r=await fetch('/api'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'请求未通过检查，请重试。');return d}
function intensity(points:Point[],t:number){
 if(t<=points[0].tick)return points[0].level;if(t>=points.at(-1)!.tick)return points.at(-1)!.level;
 const h=points.slice(1).map((p,i)=>p.tick-points[i].tick),d=h.map((v,i)=>(points[i+1].level-points[i].level)/v),slopes=points.map(()=>0);
 for(let i=1;i<points.length-1;i++)if(d[i-1]*d[i]>0){const w1=2*h[i]+h[i-1],w2=h[i]+2*h[i-1];slopes[i]=(w1+w2)/(w1/d[i-1]+w2/d[i]);}
 let i=0;while(i+1<points.length&&t>=points[i+1].tick)i++;const u=(t-points[i].tick)/h[i];
 return Math.max(0,Math.min(1,(2*u**3-3*u*u+1)*points[i].level+(u**3-2*u*u+u)*h[i]*slopes[i]+(-2*u**3+3*u*u)*points[i+1].level+(u**3-u*u)*h[i]*slopes[i+1]));
}
function Melody({m,w=180,h=38}:{m:Material;w?:number;h?:number}){const lo=Math.min(55,...m.notes.map(n=>n.pitch)),hi=Math.max(75,...m.notes.map(n=>n.pitch));return <svg viewBox={`0 0 ${w} ${h}`} width="100%" height={h} aria-hidden="true">{m.notes.map((n,i)=><line key={i} x1={3+n.start_tick/m.length_ticks*(w-6)} x2={Math.min(w-3,3+(n.start_tick+n.duration_tick)/m.length_ticks*(w-6))} y1={5+(hi-n.pitch)/(hi-lo)*(h-10)} y2={5+(hi-n.pitch)/(hi-lo)*(h-10)} stroke="currentColor" strokeWidth="3" strokeLinecap="round"/>)}</svg>}
function App(){
 const [p,setP]=useState<Project|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[theme,setTheme]=useState(localStorage.getItem('theme')||'light'),[sample,setSample]=useState('joy');
 const reviewing=new URLSearchParams(location.search).get('review')==='roles';
 const [samples,setSamples]=useState<Sample[]>([]);
 const [material,setMaterial]=useState(''),[selected,setSelected]=useState(''),[method,setMethod]=useState('variant'),[cell,setCell]=useState(0),[tool,setTool]=useState('select'),[points,setPoints]=useState<Point[]|null>(null),[dragTick,setDragTick]=useState<number|null>(null);
 const [job,setJob]=useState(''),[progress,setProgress]=useState<ProgressState|null>(null),[mode,setMode]=useState('melody_only'),[candidate,setCandidate]=useState(''),[kind,setKind]=useState('final'),[preview,setPreview]=useState<Material|null>(null),[playing,setPlaying]=useState(false),[playerLabel,setPlayerLabel]=useState('选择素材或成品试听');
 const [resultInfo,setResultInfo]=useState(''),[performanceNotice,setPerformanceNotice]=useState(false);
 const noticeDialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const dialog=noticeDialog.current;if(!dialog)return;if(performanceNotice&&!dialog.open)dialog.showModal();else if(!performanceNotice&&dialog.open)dialog.close()},[performanceNotice]);
 useEffect(()=>setResultInfo(''),[candidate,kind,p?.fingerprint]);
 const playback=useRef(0);
 const svg=useRef<SVGSVGElement>(null),audio=useRef<HTMLAudioElement>(null),ctx=useRef<AudioContext|null>(null),timer=useRef<number>(0),draft=useRef<Point[]|null>(null),gesture=useRef<{kind:string;index?:number;id?:string;offset?:number;tick?:number}|null>(null);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('theme',theme)},[theme]);
 useEffect(()=>{api('/samples').then(setSamples).catch(e=>setError(e.message))},[]);
 useEffect(()=>{(new URLSearchParams(location.search).get('example')==='joy'?api('/session',{sample:'joy',example:true}).then(next=>{setP(next);setMode('arranged');history.replaceState(null,'',location.pathname)}):api('/project').then(next=>{setP(next);const applied=next.candidates.find((c:Candidate)=>c.applied);if(applied){setCandidate(applied.id);if(applied.mode)setMode(applied.mode);setPlayerLabel("已确认方案 · 点击播放试听")}}).catch(()=>api('/session',{sample:'joy'}).then(setP))).catch(e=>setError(e.message));return()=>{playback.current++;ctx.current?.close();clearTimeout(timer.current)}},[]);
 function stop(){playback.current++;audio.current?.pause();if(audio.current)audio.current.currentTime=0;ctx.current?.close();ctx.current=null;clearTimeout(timer.current);setPlaying(false)}
 async function update(action:string,args:unknown={}){if(!p||busy)return false;setBusy(true);setError('');try{setP(await api('/edit',{fingerprint:p.fingerprint,action,args}));setCandidate('');setJob('');setProgress(null);return true}catch(e){setError((e as Error).message);setP(await api('/project'));return false}finally{setBusy(false)}}
 async function clearBoard(){stop();if(await update('clear_canvas')){setSelected('');setCell(0);setPoints(null);draft.current=null;gesture.current=null;setDragTick(null);setPreview(null);setPlayerLabel('选择素材或成品试听')}}
 async function reset(){stop();setBusy(true);try{setP(await api('/session',{sample}));history.replaceState(null,'',location.pathname);setSelected('');setMaterial('');setJob('');setProgress(null);setCandidate('');setPreview(null);setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{if(!job)return;let done=false;const tick=async()=>{try{const j=await api('/jobs/'+job);if(done)return;
  if(['QUEUED','RUNNING'].includes(j.status)){setProgress(old=>({step:Math.max(old?.step||0,progressStep(j.progress.phase)),phase:j.progress.phase,status:j.status==='QUEUED'?'queued':'running'}));return}
  const next=await api('/project');if(done)return;setP(next);setJob('');
  const finished=['SUCCEEDED','INSUFFICIENT'].includes(j.status)&&next.candidates.length>0;
  setProgress(old=>({step:finished?8:j.status==='CANCELLED'?0:old?.step||0,status:finished?'done':j.status==='CANCELLED'?'cancelled':'failed'}));
  if(j.error&&j.status!=='CANCELLED')setError(j.error);else if(!finished&&j.status!=='CANCELLED')setError('未找到有效方案，请调整素材或空缺。');
 }catch(e){if(!done){setError((e as Error).message);setProgress(old=>({step:old?.step||0,status:'failed'}));setJob('')}}};tick();const id=setInterval(tick,2000);return()=>{done=true;clearInterval(id)}},[job]);
 async function generate(){if(!p||busy||job)return;setPerformanceNotice(true);setBusy(true);setError('');try{const j=await api('/generate',{fingerprint:p.fingerprint,mode});setProgress({step:0,status:'queued'});setJob(j.id)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function cancelGeneration(){if(!job||busy)return;setBusy(true);try{await api('/jobs/'+job+'/cancel',{})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function play(materialPreview:Material|null=preview){stop();setError('');const request=playback.current;
  if(materialPreview){const ac=new AudioContext();ctx.current=ac;try{await ac.resume();if(request!==playback.current)return;const start=ac.currentTime+.04;for(const n of materialPreview.notes){const o=ac.createOscillator(),g=ac.createGain();o.type='triangle';o.frequency.value=440*2**((n.pitch-69)/12);o.connect(g);g.connect(ac.destination);const t=start+n.start_tick/480*.5,d=Math.max(.05,n.duration_tick/480*.5);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.09,t+.01);g.gain.setValueAtTime(.09,Math.max(t+.01,t+d-.03));g.gain.linearRampToValueAtTime(0,t+d);o.start(t);o.stop(t+d+.01)}setPlaying(true);timer.current=window.setTimeout(()=>{if(request===playback.current){setPlaying(false);ctx.current=null}void ac.close()},materialPreview.length_ticks/480*500+100)}catch{if(request===playback.current){setPlaying(false);setError('素材试听未能启动，请再点击播放。')}}
  }else if(candidate){setPlayerLabel((kind==='final'?'连接后的成品':'补全后的原始拼接')+' · 方案 '+(p!.candidates.findIndex(c=>c.id===candidate)+1));audio.current!.src=`/api/assets/${candidate}/${kind}/wav`;try{await audio.current!.play();if(request===playback.current)setPlaying(true)}catch{if(request===playback.current)setError('音频不可用，请重新生成。')}}
 }
 function audition(m:Material){setPreview(m);setCandidate('');setPlayerLabel(m.display_name+' · 素材音高预览');if(audio.current){audio.current.removeAttribute('src');audio.current.load()}void play(m)}
 const result=kind==='final'?p?.candidates.find(c=>c.id===candidate)?.result:undefined;
 const W=Math.max(850,(p?.grid_count||8)*(result?120:86)),H=340,pad=34;
 function coords(e:{clientX:number;clientY:number}){const r=svg.current!.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
 function tickAt(x:number){return Math.max(0,Math.min(p!.total_ticks,Math.round((x-pad)/(W-pad-16)*p!.total_ticks/480)*480))}
 function xAt(t:number){return pad+t/p!.total_ticks*(W-pad-16)}
 function move(e:React.PointerEvent<SVGSVGElement>){const g=gesture.current;if(!g||!p||result)return;const pos=coords(e),t=tickAt(pos.x),v=Math.max(0,Math.min(1,(H-45-pos.y)/(H-90)));if(g.kind==='block'){g.tick=Math.max(0,t-(g.offset||0));setDragTick(g.tick);return}let next=[...(draft.current||p.intensity_points)];if(g.kind==='point'){const i=g.index!;next[i]={tick:i===0?0:i===next.length-1?p.total_ticks:Math.max(next[i-1].tick+1,Math.min(next[i+1].tick-1,t)),level:v}}else{next=next.filter(pt=>pt.tick!==t);next.push({tick:t,level:v});next.sort((a,b)=>a.tick-b.tick)}draft.current=next;setPoints(next)}
 function end(){const g=gesture.current;gesture.current=null;if(!g||result)return;if(g.kind==='block'){if(g.tick!==undefined)update('move',{placement_id:g.id,start_tick:g.tick});setDragTick(null)}else if(draft.current){update(g.kind==='draw'?'set_trace':'set_intensity',{points:draft.current});draft.current=null;setPoints(null)}}
 if(!p)return <main className="loading">EmoBlocks · 正在准备旋律积木…{error&&<p role="alert">{error}</p>}</main>;
 const hasCanvasContent=p.placements.length>0||p.blanks.length>0||p.intensity_points.length>2||p.intensity_points.some(pt=>pt.level!==.25);
 const block=p.placements.find(b=>b.id===selected),mat=p.materials.find(m=>m.id===material),pts=points||p.intensity_points,source=samples.find(s=>s.id===sample);
 return <><header><div className="brand"><img className="brandmark" src={brandIcon} width="36" height="36" alt=""/>EmoBlocks <small>情绪积木</small></div><span className="badge">在线体验</span><span className="spacer"/><span className="save-state">自动保存 · 24 小时</span><button title="切换明暗主题" aria-label="切换明暗主题" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☀':'☾'}</button></header>
 <dialog ref={noticeDialog} className="generation-notice" aria-labelledby="generation-notice-title" aria-describedby="generation-notice-text" onCancel={()=>setPerformanceNotice(false)} onClose={()=>setPerformanceNotice(false)}><h2 id="generation-notice-title">生成提示</h2><p id="generation-notice-text">服务器性能低下，复杂任务可能耗时过长，本地更快速</p><div className="notice-actions"><button type="button" onClick={()=>setPerformanceNotice(false)}>知道了</button></div></dialog>
 <div className="workspace"><aside className="sources"><div className="sectionhead"><h2>旋律原料</h2><span className="muted">01</span></div><p className="muted">从一小段灵感开始</p><label className="field">内置旋律<select value={sample} onChange={e=>setSample(e.target.value)}>{samples.map(s=><option value={s.id} key={s.id}>{s.label}</option>)}</select></label><button className="wide" disabled={busy||!!job||!source} onClick={reset}>载入旋律 · 新体验</button><p className="source-note">内置素材可直接体验。公开 Demo 暂不接收上传或录音。</p>{source&&<details className="source-note"><summary>素材来源与许可</summary><p>{source.composer}<br/>{source.credit}<br/>{source.adaptation}</p>{source.source.startsWith('https://')&&<a href={source.source} target="_blank" rel="noreferrer">乐谱来源</a>}<p>{source.license_url?<a href={source.license_url} target="_blank" rel="noreferrer">{source.license}</a>:source.license}</p></details>}<div className="workflow"><h3>让音乐跟随你的设计</h3><ol><li>绘制情绪起伏</li><li>在指定位置放入旋律</li><li>试听补齐与连接方案</li><li>确认、调整并导出</li></ol></div><div className="source-footer">规则算法驱动当前体验<br/>工作流预留模型适配接口</div></aside>
 <section className="library"><div className="sectionhead"><h2>音乐积木库</h2><span className="muted">{p.materials.filter(m=>m.library_visible).length}</span></div><p className="muted">拖入画布，自主搭建</p><div className="cards">{p.materials.filter(m=>m.library_visible).map((m,i)=><article className={'material '+(material===m.id?'chosen':'')} style={{'--note':Object.values(emotions)[i%6][1]} as React.CSSProperties} key={m.id} draggable onDragStart={e=>{e.dataTransfer.setData('text/plain',m.id);e.dataTransfer.effectAllowed='copy';setMaterial(m.id)}} onClick={()=>setMaterial(m.id)}><div className="cardtop"><button className="cardselect" aria-label={'选择 '+m.display_name} title={m.label} onClick={()=>setMaterial(m.id)}>{m.display_name}{m.kind==='phrase'?' · 乐句':m.kind==='bridge'?' · Bridge':''}</button><span>{m.length_ticks/480} 拍</span><button className="icon" aria-label={'播放 '+m.display_name} title="立即试听旋律" onClick={e=>{e.stopPropagation();audition(m)}}>▷</button></div><Melody m={m}/></article>)}</div><div className="derive"><select aria-label="新旋律方式" value={method} onChange={e=>setMethod(e.target.value)}>{Object.entries(methods).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><button disabled={!mat||busy||!!job} onClick={()=>update('derive',{material_id:material,method})}>新旋律</button></div></section>
 <main className="studio">{reviewing&&<div className="status">本地用途验收示例 · 使用专门的演示旋律，非《欢乐颂》。</div>}<div className="sectionhead"><div><div className="board-heading"><h1>情绪搭建画板</h1><button className="clear-board" disabled={busy||(!hasCanvasContent&&!job)} title="清除积木和强度线，保留素材库；可撤销" onClick={()=>void clearBoard()}>清空画板</button></div><p className="muted">决定何时出现什么旋律，让起伏贴合你的情节。</p></div><div className="tools"><button disabled={!p.can_undo||busy} title="撤销" onClick={()=>update('undo')}>↶</button><button disabled={!p.can_redo||busy} title="重做" onClick={()=>update('redo')}>↷</button><span className="divider"/><button aria-label="减少四拍" disabled={p.grid_count<=1||busy} onClick={()=>update('resize',{grid_count:p.grid_count-1})}>−</button><span>{p.grid_count*4} 拍</span><button aria-label="增加四拍" disabled={p.grid_count>=32||busy} onClick={()=>update('resize',{grid_count:p.grid_count+1})}>＋</button></div></div>
 <div className="canvas-tools"><div className="segmented">{[['select','选择 / 调整'],['draw','手绘强度']].map(([k,v])=><button key={k} disabled={!!result} className={tool===k?'active':''} onClick={()=>setTool(k)}>{v}</button>)}</div>{!result&&<span className="muted">先画起伏，再放积木</span>}<span className="spacer"/><span className="memory-label">▰ {p.memory.state==='BOUND'?'记忆积木已保护':p.memory.state==='PENDING_GAP'?'峰值等待落位':'峰值保持留白'}</span></div>
 <div className="canvas-scroll"><svg ref={svg} className="canvas" width={W} height={H} viewBox={`0 0 ${W} ${H}`} aria-label="情绪强度与旋律积木画布" onDragOver={e=>{e.preventDefault();if(result)return;setDragTick(tickAt(coords(e).x))}} onDragLeave={()=>setDragTick(null)} onDrop={e=>{e.preventDefault();if(result)return;const id=e.dataTransfer.getData('text/plain');setDragTick(null);if(p.materials.some(m=>m.id===id))update('place',{material_id:id,start_tick:tickAt(coords(e).x)})}} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{gesture.current=null;setPoints(null);draft.current=null;setDragTick(null)}} onKeyDown={e=>{if(e.key==='Escape'){gesture.current=null;setPoints(null);draft.current=null;setDragTick(null)}}} onPointerDown={e=>{if(result||e.target!==e.currentTarget)return;setCell(Math.min(p.grid_count-1,Math.floor(tickAt(coords(e).x)/1920)));setSelected('');if(tool==='draw'){gesture.current={kind:'draw'};draft.current=[...p.intensity_points];e.currentTarget.setPointerCapture(e.pointerId);move(e)}}}>
 {[0,.25,.5,.75,1].map(v=><g key={v} pointerEvents="none"><line className="gridline" x1={pad} x2={W-16} y1={H-45-v*(H-90)} y2={H-45-v*(H-90)}/><text className="axis" x={3} y={H-41-v*(H-90)}>{v*100}</text></g>)}
 {Array.from({length:p.grid_count},(_,i)=><g key={i} pointerEvents="none"><rect x={xAt(i*1920)} y={H-33} width={(W-pad-16)/p.grid_count} height={25} fill={cell===i?'var(--selected)':'transparent'}/><line className="gridline" x1={xAt(i*1920)} x2={xAt(i*1920)} y1={30} y2={H-38}/><text className="axis" x={xAt(i*1920)+8} y={H-15}>{i+1}</text></g>)}
 {!result&&p.blanks.map(b=><g key={b.id} role="button" tabIndex={0} aria-label="取消主动留白" onClick={()=>update('delete_blank',{blank_id:b.id})} onKeyDown={e=>{if(e.key==='Enter')update('delete_blank',{blank_id:b.id})}}><rect x={xAt(b.start_tick)} y={40} width={xAt(b.end_tick)-xAt(b.start_tick)} height={H-90} fill="var(--blank)" stroke="var(--border)" strokeDasharray="4 5"/><text className="axis" x={xAt(b.start_tick)+6} y={H-64}>留白 ×</text></g>)}
 <polyline fill="none" stroke="var(--accent)" strokeWidth="2" points={Array.from({length:161},(_,i)=>{const t=p.total_ticks*i/160;return `${xAt(t)},${H-45-intensity(pts,t)*(H-90)}`}).join(' ')} pointerEvents="none"/>
 {!result&&p.placements.map(b=>{const t=gesture.current?.id===b.id&&dragTick!==null?dragTick:b.start_tick,x=xAt(t),w=xAt(t+b.length_ticks)-xAt(t),y=H-45-intensity(pts,t+b.length_ticks/2)*(H-90)-31;return <g key={b.id} className={'block '+(selected===b.id?'block-selected':'')} tabIndex={0} role="button" aria-label={'选择积木 '+b.base_snapshot.display_name} onKeyDown={e=>{if(e.key==='Enter')setSelected(b.id);if(e.key==='Delete'||e.key==='Backspace')update('delete',{placement_id:b.id})}} onPointerDown={e=>{e.stopPropagation();setSelected(b.id);gesture.current={kind:'block',id:b.id,offset:tickAt(coords(e).x)-b.start_tick};setDragTick(null);svg.current!.setPointerCapture(e.pointerId)}}><rect x={x+2} y={y} width={Math.max(6,w-4)} height={62} rx={7} fill={emotions[b.emotion]?.[1]||'#9cdcc6'}/><svg x={x+6} y={y+5} width={Math.max(2,w-12)} height={52} overflow="hidden"><text x={3} y={12} fontSize={11} fill="#263234">{b.base_snapshot.display_name}</text><text x={3} y={25} fontSize={10} fill="#263234">{emotions[b.emotion]?.[0]}</text><g transform="translate(1 29)" color="#365052"><Melody m={b.base_snapshot} w={Math.max(8,w-16)} h={21}/></g></svg>{p.memory.placement_id===b.id&&<g pointerEvents="none"><rect x={x+7} y={y-17} width={50} height={17} rx={3} fill="var(--text)"/><text x={x+12} y={y-5} fontSize={10} fill="var(--surface)">记忆积木</text></g>}</g>})}
 {result&&<ResultBlocks segments={result.segments} onInspect={setResultInfo} xAt={xAt} yAt={t=>H-45-intensity(pts,t)*(H-90)} emotions={emotions} melody={(s,w)=><Melody m={{id:s.id,label:s.display_name,display_name:s.display_name,library_visible:false,length_ticks:s.end_tick-s.start_tick,kind:s.role,notes:s.notes}} w={w} h={21}/>}/>}
 {!result&&p.protections.filter(r=>r.kind==='bridge').map((r,i)=><g key={'bridge'+i} pointerEvents="none"><line x1={xAt(r.start_tick)+3} x2={xAt(r.end_tick)-3} y1={H-37} y2={H-37} stroke="var(--accent)" strokeWidth={2}/><text className="axis" x={xAt(r.start_tick)+5} y={H-47}>Bridge · 已保护</text></g>)}
 {pts.map((pt,i)=><circle key={i} className="point" cx={xAt(pt.tick)} cy={H-45-pt.level*(H-90)} r={5} tabIndex={result?-1:0} role="slider" aria-disabled={!!result} aria-label={'强度控制点 '+(i+1)} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(pt.level*100)} onKeyDown={e=>{if(result)return;if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();update('set_intensity',{points:pts.map((v,j)=>j===i?{...v,level:Math.max(0,Math.min(1,v.level+(e.key==='ArrowUp'?.05:-.05)))}:v)})}}} onPointerDown={e=>{e.stopPropagation();if(result)return;gesture.current={kind:'point',index:i};draft.current=[...pts];svg.current!.setPointerCapture(e.pointerId)}}/>)}
 {dragTick!==null&&<line pointerEvents="none" x1={xAt(dragTick)} x2={xAt(dragTick)} y1={20} y2={H-35} stroke="var(--accent)" strokeDasharray="5 4"/>}
 </svg></div>
 {result&&<div className="result-legend" aria-label="成品积木用途"><strong>成品用途预览 · 只读</strong>{[...new Set(result.segments.map(s=>s.role_label))].map(label=><span key={label}>{label}</span>)}<button onClick={()=>{stop();setCandidate('');setPlayerLabel('选择素材或成品试听')}}>返回搭建</button><small role="status">{resultInfo||'短片段竖排标记；悬停或聚焦查看拍数与用途。'}</small></div>}
 {!result&&<div className="selection">{block?<><span className="selected-name">{block.base_snapshot.display_name}</span><div className="emotion-options">{Object.entries(emotions).map(([k,[name,color]])=><button key={k} className={block.emotion===k?'active':''} onClick={()=>update('set_emotion',{placement_ids:[block.id],emotion:k})}><i style={{background:color}}/>{name}</button>)}</div><span className="spacer"/><button onClick={()=>update('delete',{placement_id:block.id})}>移除</button></>:<><label className="muted">第 <input aria-label="放置格" type="number" min={1} max={p.grid_count} value={cell+1} onChange={e=>setCell(Math.max(0,Math.min(p.grid_count-1,+e.target.value-1)))}/> 格</label><button disabled={!mat||busy} onClick={()=>update('place',{material_id:material,start_tick:cell*1920})}>放入所选积木</button><button onClick={()=>update('mark_blank',{start_tick:cell*1920,end_tick:(cell+1)*1920})}>标为留白</button><span className="muted">空缺参与补齐；留白保留呼吸。</span></>}</div>}
 <div className="generation"><div><h3>智能加工</h3></div><span className="spacer"/><select aria-label="编配模式" value={mode} onChange={e=>setMode(e.target.value)}><option value="melody_only">仅主旋律</option><option value="arranged">完整编配</option></select><button className="primary" disabled={busy||!!job||!p.placements.length} onClick={generate}>生成方案</button></div>
 {progress&&<GenerationProgress value={progress} disabled={busy} onCancel={job?()=>void cancelGeneration():undefined}/>}
 {error&&<div className="error" role="alert">{error}<button aria-label="关闭提示" onClick={()=>setError('')}>×</button></div>}
 {!!p.candidates.length&&<div className="candidates">{p.candidates.map((c,i)=><button className={candidate===c.id?'candidate active':'candidate'} key={c.id} onClick={()=>{stop();setPreview(null);setSelected('');setCandidate(c.id);setPlayerLabel('方案 '+(i+1)+' · 点击播放试听')}}><strong>方案 {i+1}</strong><span>真实生成 · {c.applied?'已确认':c.changed?'连接已调整':'保留原拼接'}</span></button>)}<button disabled={busy||!candidate||!p.candidates.find(c=>c.id===candidate)?.ready} onClick={async()=>{setBusy(true);try{setP(await api('/confirm',{fingerprint:p.fingerprint,candidate_id:candidate}));setSelected('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>确认所选方案</button>{p.candidates.length<2&&<span className="muted">当前仅有一套满足约束的方案。</span>}</div>}
 <footer className="player"><div className="player-title"><span className="kicker">试听与导出</span><strong>{playerLabel}</strong></div><button className="play" aria-label="播放" disabled={!preview&&!candidate} onClick={()=>void play()}>{playing?'↻':'▶'}</button><button aria-label="停止" onClick={stop}>■</button><audio ref={audio} controls onEnded={()=>{if(!ctx.current)setPlaying(false)}} onPlay={()=>{if(!ctx.current)setPlaying(true)}} onPause={()=>{if(!ctx.current)setPlaying(false)}}/>{candidate&&<><select aria-label="对比版本" value={kind} onChange={e=>{stop();setKind(e.target.value);setPreview(null)}}><option value="comparison">原始拼接</option><option value="final">连接成品</option></select><div className="exports">{['wav','mid','mmp'].map(f=><a key={f} href={`/api/assets/${candidate}/final/${f}`} download>{f==='mid'?'MIDI':f.toUpperCase()}</a>)}</div></>}</footer>
 <p className="scope">在线 Demo 使用真实补全、连接与 LMMS 渲染。完整桌面工作流支持 MIDI / MMP 导入；哼唱与外部模型不在本次公开体验范围内。</p>
 <p className="deployment-note">在线 Demo 受服务器性能限制，完整功能建议本地部署体验。<a href="https://github.com/limgong/EmoBlock" target="_blank" rel="noopener noreferrer">GitHub 仓库与部署说明 ↗</a></p></main></div></>;
}
createRoot(document.getElementById('root')!).render(<App/>);
